services:
  - type: web
    name: farmacia-backend
    runtime: node
    repo: https://github.com/Diego-242/SistemaFarmacia.git
    plan: free
    rootDir: backend
    buildCommand: pnpm install && npx prisma generate && npx prisma db push
    startCommand: node index.js
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: farmacia-frontend
    runtime: node
    repo: https://github.com/Diego-242/SistemaFarmacia.git
    plan: free
    rootDir: frontend
    buildCommand: pnpm install && pnpm run build
    startCommand: node ./dist/server/entry.mjs
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PUBLIC_API_URL
        value: https://farmacia-backend.onrender.com